### ISSUE TITLE
Add gitignore and remove __pycache__ folder

### ISSUE THREAD

**Issue by nishithshah2211** [Furyz1/shc#17]

**Comment by Furyz1** [comment]
Good point, can you do a pull request ?

**Comment by nishithshah2211** [comment]
Yes, sure. Working on it.

**Comment by amitsharma928** [comment]
Hi @nishithshah2211 and @Furyz1 if you don't mind can I do this? I found it easy, also it is my first PR on github.

**Comment by nishithshah2211** [comment]
Hey @amitsharma928 , I am really sorry, I didn't see this comment before making a PR.
I can help you with other issues that have been opened in this repo, as they too seem fairly easy for a first PR.
Really sorry.

**Comment by amitsharma928** [comment]
@nishithshah2211 No problem :) help me to resolve other issues.

**Comment by nishithshah2211** [comment]
Thanks @Furyz1 

@amitsharma928 Sure, let me know which issue you want to get started with, and we can take it from there.
